before:
  hooks:
  - make dep

builds:
  - binary: testci
    main: ./
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CGO_ENABLED=0
    ldflags:
      - -a -installsuffix cgo
      - -X main.gitTag={{.Tag}}
      - -s
      - -w

archives:
  - builds: [testci]

nfpms:
  - vendor: testci
    homepage: https://github.com/shdubna/testci
    maintainer: Aleksandr Smirnov
    description: Export metrics from zabbix server/.
    license: Apache2
    formats: [ deb, rpm, apk ]
    bindir: /usr/bin